"""
evidence.py — read-only endpoints serving the project's measurement record
==========================================================================

Backs the dashboard's Analytics page. Everything here reads a committed
artifact off disk; nothing is computed at request time and nothing is
estimated.

The governing rule (CLAUDE.md): *nothing may imply a result exists until
`training-agent` + `verify_results.py` say so.* So every payload carries an
explicit `provenance`, and anything short of VERIFIED also carries a
`caveat` spelling out what the reader must not conclude. The frontend
renders both — it does not get to decide how trustworthy a number is, the
backend tells it. This is deliberate: the one Analytics bug this project
has already had (a fabricated "100% energy saved" KPI, found 2026-08-22)
came from the UI inferring a result the data did not support.

Statuses mirror `paper/results.md`'s verdict column:

    VERIFIED   verify_results.py PASS — safe to present as a result
    CONTENDED  real measurement, but taken under host contention; not
               gate-eligible, some tiers inflated
    DERIVED    computed from committed inputs, not a GPU measurement
    PENDING    the session has not produced data yet — never fabricate

Mounted by api.py as `router`, under the /evidence prefix.
"""

import csv
import json
import re
from pathlib import Path

from fastapi import APIRouter

router = APIRouter(prefix="/evidence", tags=["evidence"])

PROVENANCE = {
    "VERIFIED": "verify_results.py PASS — safe to cite",
    "CONTENDED": "real measurement taken under host contention — not gate-eligible",
    "DERIVED": "computed from committed inputs, not a GPU measurement",
    "PENDING": "no data yet — this session has not been run",
}


def _project_root() -> Path:
    """major-project/ — this file sits at backend/src/green_weight/."""
    return Path(__file__).resolve().parents[3]


def _read_csv_rows(path: Path):
    if not path.exists():
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _num(value):
    """CSV cells arrive as strings. Make the numeric ones real numbers so
    the frontend never has to parseFloat a display value."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return value


def _parse_md_table(text: str, expected_cols: int):
    """Cell-lists for every row of the markdown tables with exactly
    `expected_cols` columns. Header and `---` separator rows dropped."""
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != expected_cols:
            continue
        if all(set(c) <= set("-: ") for c in cells if c):
            continue
        rows.append(cells)
    return rows


@router.get("/validation")
def validation():
    """The automated gate's own verdict — verify_results.py's report.

    This is the project's approval record: which checks passed, which
    warned, which failed. Served row-for-row rather than summarised, so
    the dashboard cannot quietly drop a FAIL.
    """
    path = _project_root() / "paper" / "results_validation.md"
    if not path.exists():
        return {"provenance": "PENDING", "note": PROVENANCE["PENDING"],
                "verdict": None, "counts": {}, "findings": []}

    text = path.read_text(encoding="utf-8")

    verdict = None
    generated_at = None
    counts = {"PASS": 0, "WARN": 0, "FAIL": 0}

    for line in text.splitlines():
        if line.startswith("**Verdict:"):
            verdict = line.split("**Verdict:")[1].split("**")[0].strip()
            m = re.search(r"PASS:\s*(\d+),\s*WARN:\s*(\d+),\s*FAIL:\s*(\d+)", line)
            if m:
                counts = {"PASS": int(m.group(1)),
                          "WARN": int(m.group(2)),
                          "FAIL": int(m.group(3))}
        elif line.startswith("Generated by") and " on " in line:
            generated_at = line.split(" on ")[-1].split(" (")[0].strip()

    findings = [
        {"level": lvl, "area": area, "finding": msg}
        for lvl, area, msg in _parse_md_table(text, 3)
        if lvl in ("PASS", "WARN", "FAIL")
    ]

    return {
        "provenance": "VERIFIED",
        "note": "verdict emitted by training/scripts/verify_results.py",
        "verdict": verdict,
        "generated_at": generated_at,
        "counts": counts,
        "findings": findings,
    }


@router.get("/experiments")
def experiments():
    """paper/results.md's append-only experiment log — the only numeric
    source the paper may cite. Served so the dashboard can show each run's
    real verdict beside its numbers."""
    path = _project_root() / "paper" / "results.md"
    if not path.exists():
        return {"provenance": "PENDING", "note": PROVENANCE["PENDING"], "runs": []}

    rows = _parse_md_table(path.read_text(encoding="utf-8"), 6)
    runs = [
        {"date": r[0], "session": r[1], "script": r[2],
         "outputs": r[3], "verdict": r[4], "finding": r[5]}
        for r in rows
        if r[0].lower() not in ("date", "")
    ]
    return {"provenance": "VERIFIED",
            "note": "transcribed from paper/results.md, the append-only log",
            "runs": runs}


@router.get("/energy")
def energy():
    """Session 1 per-tier energy — the project's one VERIFIED quantitative
    result (verify_results.py PASS, n=1500/tier, 3 runs, seed=42)."""
    rows = _read_csv_rows(_project_root() / "results" / "energy_summary.csv")
    if not rows:
        return {"provenance": "PENDING", "note": PROVENANCE["PENDING"], "tiers": []}

    tiers = [{
        "tier": r.get("tier"),
        "n": _num(r.get("n")),
        "mean_j_per_token": _num(r.get("mean_j_per_token")),
        "std": _num(r.get("std")),
        "ci95": _num(r.get("ci95")),
    } for r in rows]

    baseline = next((t["mean_j_per_token"] for t in tiers if t["tier"] == "16bit"), None)
    for t in tiers:
        # Ratio of two measured means: arithmetic on VERIFIED numbers, not
        # a new claim. The UI labels this "cost vs fp16", never "saved by
        # routing" — a static tier is not the router.
        if baseline and isinstance(t["mean_j_per_token"], float):
            t["ratio_vs_16bit"] = round(t["mean_j_per_token"] / baseline, 4)

    return {
        "provenance": "VERIFIED",
        "note": PROVENANCE["VERIFIED"],
        "session": "Session 1 — energy ground truth (2026-09-04)",
        "hardware": "NVIDIA RTX 6000 Ada Generation, driver 610.43.02, idle 22.53 W",
        "method": ("NVML nvmlDeviceGetTotalEnergyConsumption, greedy decoding, "
                   "max_new_tokens=128, 500-prompt eval set, 3 runs, seed=42"),
        "caveat": ("Cost of running each tier. This is NOT an energy saving from "
                   "routing — that is Session 4, which has no gate-eligible run yet."),
        "tiers": tiers,
    }


@router.get("/routing")
def routing():
    """Session 4 routing conditions. Both existing runs are CONTENDED —
    measured while the GPU host was shared, so some tiers are inflated and
    neither counts toward the gate. Both also predate the 2026-09-09
    router fixes, so they measure the OLD routing policy."""
    root = _project_root()
    runs = []
    for label, fname, detail in (
        ("run 1 — job 1505, by-tier", "routing_run1_conditions.csv",
         "4-bit/8-bit measured pre-contention and match Session 1; 16-bit inflated 45%"),
        ("run 2 — job 1507, interleaved", "routing_run2_conditions.csv",
         "16-bit accurate to 1.6%; 4-bit/8-bit inflated 3-5x"),
    ):
        rows = _read_csv_rows(root / fname)
        if not rows:
            continue
        runs.append({
            "run": label,
            "source": fname,
            "contention_detail": detail,
            "conditions": [{
                "condition": r.get("condition"),
                "accuracy": _num(r.get("accuracy")),
                "j_per_request": _num(r.get("j_per_request")),
                "j_per_token": _num(r.get("j_per_token")),
                "mean_latency_s": _num(r.get("mean_latency_s")),
                "n_prompts": _num(r.get("n_prompts")),
                "pct_4bit": _num(r.get("pct_4bit")),
                "pct_8bit": _num(r.get("pct_8bit")),
                "pct_16bit": _num(r.get("pct_16bit")),
            } for r in rows],
        })

    if not runs:
        return {"provenance": "PENDING", "note": PROVENANCE["PENDING"], "runs": []}

    return {
        "provenance": "CONTENDED",
        "note": PROVENANCE["CONTENDED"],
        "caveat": (
            "Neither run is gate-eligible: both were measured under host "
            "contention, and both predate the 2026-09-09 router fixes, so they "
            "measure the OLD routing policy (see ROUTER_DIAGNOSIS.md). The "
            "`accuracy` column is a coarse reference-match proxy scoring "
            "0.11-0.26, NOT lm-eval benchmark accuracy — Session 2 has not run. "
            "Do not read these as the system's performance."
        ),
        "runs": runs,
    }


@router.get("/router-quality")
def router_quality():
    """Routing-decision precision / recall / F1, from the artifact written
    by training/scripts/router_quality_report.py. That file carries its own
    provenance and caveat fields; they are served through unchanged."""
    path = Path("results") / "router_quality.json"
    if not path.exists():
        return {"provenance": "PENDING",
                "note": "run training/scripts/router_quality_report.py to generate",
                "overall": {}, "per_tier": {}}
    with open(path, encoding="utf-8") as f:
        return json.load(f)
