"""
Tests for evidence.py — the read-only endpoints backing the dashboard's
Analytics page.

These exist mainly to pin one property: **an unverified number must never
be served with a status that lets the UI present it as a result.** That is
CLAUDE.md's governing rule, and the dashboard has already shipped a bug of
exactly this shape once (a fabricated "100% energy saved" KPI computed from
zero measurements, found 2026-08-22). The frontend renders whatever
`provenance` the backend sends, so the backend is the place to enforce it.

Also pinned: a missing artifact degrades to PENDING with empty data. It
must never fall back to a plausible-looking placeholder.
"""

import json

import pytest

import evidence


VALID_PROVENANCE = {"VERIFIED", "CONTENDED", "DERIVED", "PENDING"}

# Endpoint callables that read repo artifacts via _project_root().
REPO_ENDPOINTS = [
    evidence.validation,
    evidence.experiments,
    evidence.energy,
    evidence.routing,
]


class TestProvenanceContract:
    """Every payload is self-describing, always."""

    @pytest.mark.parametrize("fn", REPO_ENDPOINTS + [evidence.router_quality])
    def test_every_response_declares_provenance(self, fn):
        payload = fn()
        assert "provenance" in payload, f"{fn.__name__} served a payload with no provenance"
        assert payload["provenance"] in VALID_PROVENANCE

    def test_energy_is_verified_and_routing_is_not(self):
        """The distinction the whole page rests on. Session 1 cleared the
        gate; Session 4's runs were measured under contention and did not.
        If these ever collapse to the same status, the dashboard starts
        presenting contended data as a result."""
        assert evidence.energy()["provenance"] == "VERIFIED"
        assert evidence.routing()["provenance"] == "CONTENDED"

    @pytest.mark.parametrize("fn", [evidence.routing, evidence.router_quality])
    def test_non_verified_payloads_carry_a_caveat(self, fn):
        payload = fn()
        if payload["provenance"] in ("CONTENDED", "DERIVED"):
            assert payload.get("caveat"), (
                f"{fn.__name__} is {payload['provenance']} but ships no caveat — "
                "the UI would render the numbers with nothing qualifying them"
            )


class TestMissingArtifactsDegradeToPending:
    """No artifact => PENDING and empty. Never a placeholder number."""

    @pytest.mark.parametrize("fn,empty_key", [
        (evidence.validation, "findings"),
        (evidence.experiments, "runs"),
        (evidence.energy, "tiers"),
        (evidence.routing, "runs"),
    ])
    def test_pending_when_project_root_has_no_artifacts(self, fn, empty_key, tmp_path, monkeypatch):
        monkeypatch.setattr(evidence, "_project_root", lambda: tmp_path)
        payload = fn()
        assert payload["provenance"] == "PENDING"
        assert payload[empty_key] == []

    def test_router_quality_pending_without_artifact(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        payload = evidence.router_quality()
        assert payload["provenance"] == "PENDING"
        assert payload["per_tier"] == {}


class TestValidationParsing:
    def test_parses_counts_verdict_and_findings(self, tmp_path, monkeypatch):
        report = (
            "# Automated Results Validation\n\n"
            "Generated by `verify_results.py` on 2026-09-08T14:51:08 (UTC).\n\n"
            "**Verdict: NOT PUBLISHABLE**  (PASS: 36, WARN: 5, FAIL: 1)\n\n"
            "| Level | Area | Finding |\n"
            "|---|---|---|\n"
            "| FAIL | accuracy (Session 2) | accuracy_summary.csv missing |\n"
            "| WARN | energy (Session 1) | hardware_info.json missing |\n"
            "| PASS | energy (Session 1) | 4500 measurement rows |\n"
        )
        paper = tmp_path / "paper"
        paper.mkdir()
        (paper / "results_validation.md").write_text(report, encoding="utf-8")
        monkeypatch.setattr(evidence, "_project_root", lambda: tmp_path)

        payload = evidence.validation()
        assert payload["verdict"] == "NOT PUBLISHABLE"
        assert payload["counts"] == {"PASS": 36, "WARN": 5, "FAIL": 1}
        assert payload["generated_at"].startswith("2026-09-08")
        assert [f["level"] for f in payload["findings"]] == ["FAIL", "WARN", "PASS"]

    def test_a_failing_check_is_never_dropped(self, tmp_path, monkeypatch):
        """The dashboard must not be able to show a clean bill of health
        while a FAIL exists in the report."""
        payload = evidence.validation()
        if payload["provenance"] == "PENDING":
            pytest.skip("no validation report in this checkout")
        n_fail_rows = sum(f["level"] == "FAIL" for f in payload["findings"])
        assert n_fail_rows == payload["counts"]["FAIL"]


class TestEnergyPayload:
    def test_ratio_is_relative_to_fp16_and_fp16_is_one(self):
        payload = evidence.energy()
        if payload["provenance"] == "PENDING":
            pytest.skip("no energy artifact in this checkout")
        ratios = {t["tier"]: t.get("ratio_vs_16bit") for t in payload["tiers"]}
        assert ratios["16bit"] == 1.0
        assert ratios["4bit"] < ratios["8bit"] < ratios["16bit"]

    def test_caveat_denies_the_routing_saving_reading(self):
        """These are per-tier costs. The single most likely misreading is
        'routing saves this much', which Session 4 has not established."""
        payload = evidence.energy()
        if payload["provenance"] == "PENDING":
            pytest.skip("no energy artifact in this checkout")
        assert "not" in payload["caveat"].lower()
        assert "routing" in payload["caveat"].lower()


class TestRoutingPayload:
    def test_caveat_names_the_proxy_metric_problem(self):
        """`accuracy` in these CSVs is a coarse reference-match proxy, not
        lm-eval benchmark accuracy. Serving it unqualified beside a column
        literally headed 'accuracy' would be misleading."""
        payload = evidence.routing()
        if payload["provenance"] == "PENDING":
            pytest.skip("no routing artifacts in this checkout")
        caveat = payload["caveat"].lower()
        assert "proxy" in caveat
        assert "lm-eval" in caveat

    def test_numeric_columns_are_numbers_not_strings(self):
        payload = evidence.routing()
        if payload["provenance"] == "PENDING":
            pytest.skip("no routing artifacts in this checkout")
        cond = payload["runs"][0]["conditions"][0]
        for key in ("accuracy", "j_per_request", "j_per_token"):
            assert isinstance(cond[key], float), f"{key} came through as {type(cond[key])}"


class TestRouterQualityPayload:
    def test_served_through_unchanged_with_its_own_caveat(self, tmp_path, monkeypatch):
        artifact = {
            "provenance": "DERIVED",
            "caveat": "labels are dataset provenance, not measured sensitivity",
            "overall": {"macro_f1": 0.5},
            "per_tier": {"4bit": {"precision": 1.0}},
        }
        results = tmp_path / "results"
        results.mkdir()
        (results / "router_quality.json").write_text(json.dumps(artifact), encoding="utf-8")
        monkeypatch.chdir(tmp_path)

        payload = evidence.router_quality()
        assert payload == artifact, "the artifact's own provenance/caveat must survive intact"


class TestMarkdownTableParser:
    def test_drops_header_and_separator_rows(self):
        text = (
            "| Level | Area | Finding |\n"
            "|---|:---:|---|\n"
            "| PASS | energy | fine |\n"
        )
        rows = evidence._parse_md_table(text, 3)
        assert rows == [["Level", "Area", "Finding"], ["PASS", "energy", "fine"]]

    def test_ignores_tables_of_other_widths(self):
        text = "| a | b |\n|---|---|\n| 1 | 2 |\n"
        assert evidence._parse_md_table(text, 3) == []


class TestNumCoercion:
    @pytest.mark.parametrize("raw,expected", [
        ("1.4138", 1.4138),
        ("1500", 1500.0),
        ("", None),
        (None, None),
        ("static_4bit", "static_4bit"),
    ])
    def test_num(self, raw, expected):
        assert evidence._num(raw) == expected
